User.create!(name: '斎藤', age: 30)
User.create!(name: '田中', age: 20)
User.create!(name: '佐藤', age: 35)
User.create!(name: '山岸', age: 40)
User.create!(name: '平', age: 25)
User.create!(name: '加藤', age: 20)
